#!/bin/sh

#
# This script will load 'swrandom' module. The module will create 
# device /dev/swrandom that can be used to read the random bytes
# generated by SwiftRNG device. Device file /dev/swrandom will
# initially be created with ROOT access permissions. 
# To add public read access to the /dev/swrandom device just 
# copy 80-swiftrng-device-access.rules file to /etc/udev/rules.d/
# directory.
#
module=swrandom

/sbin/insmod ./$module.ko $* || exit 1
major="$(awk "\$2==\"$module\" {print \$1}" /proc/devices)"
echo "Module $module loaded with major number $major"

